### ISSUE TITLE
抱歉，问个问题？

### ISSUE THREAD

**Issue by shelken** [piyoki/dotfiles.nix#4]
> 抱歉，特意开个issue。因为实在联系不到你（Discord群组没回复，telegram群组链接也挂了）。
## 正题
我想知道你是怎么在更新 dotfiles 中某个input之后，如何出发这个dotfiles的Workflow更新lock的？我看你应该不是手动触发的吧？而且我也没有看到你的action有自动触发的操作？麻烦指导下，我参考一下。谢谢！

> 还有，顺便留个X或者电报吧，方便请教交流下

**Comment by piyoki** [comment]
> > 抱歉，特意开个issue。因为实在联系不到你（Discord群组没回复，telegram群组链接也挂了）。
> 
> ## 正题
> 我想知道你是怎么在更新 dotfiles 中某个input之后，如何出发这个dotfiles的Workflow更新lock的？我看你应该不是手动触发的吧？而且我也没有看到你的action有自动触发的操作？麻烦指导下，我参考一下。谢谢！
> 
> > 还有，顺便留个X或者电报吧，方便请教交流下

Pasted the link to you in Discord.
